CREATE TABLE inquiries(
    id SERIAL NOT NULL,
    user_id integer NOT NULL,
    room_id integer NOT NULL,
    room_name varchar(255) NOT NULL,
    room_type varchar(255) NOT NULL,
    room_capacity integer NOT NULL,
    room_price integer NOT NULL,
    date_reservation date NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone NOT NULL,
    duration integer NOT NULL,
    name varchar(255) NOT NULL,
    phone varchar(20) NOT NULL,
    company varchar(255) NOT NULL,
    participants integer NOT NULL,
    snack_id integer,
    snack_name varchar(255),
    snack_category varchar(100),
    snack_price integer,
    total_room_price integer NOT NULL,
    total_snack_price integer NOT NULL,
    total_price integer NOT NULL,
    notes text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT inquiry_user_id_fkey FOREIGN key(user_id) REFERENCES users(id),
    CONSTRAINT inquiry_room_id_fkey FOREIGN key(room_id) REFERENCES rooms(id),
    CONSTRAINT inquiry_snack_id_fkey FOREIGN key(snack_id) REFERENCES snacks(id)
);